### PR TITLE
MGTOW coin

### PR DESCRIPTION
**Pull request by eliskcage**
I'm trying to create a new coin.
Many thanks.

### CODE REVIEW

**Comment by vvlancetov** [comment]
MGTOWcoin? That is fun ))

**Comment by eliskcage** [comment]
yes, I need some help to get it off the ground. I've already been involved
in the creation of the redpill coin, Angry mgtow has created and is
distributing at the moment. Let me know if you have any more interest, I'd
be happy to chat.

**Comment by eliskcage** [comment]
If u can send me the link to the seethemturn shout out ill b on board.

**Comment by boda21** [comment]
Hello can you pls contact me for

**Comment by SoraKohaku** [comment]
telegram?

**Comment by boda21** [comment]
I need to get in contact with eliskcage

**Comment by boda21** [comment]
Telegram is fine. how do i get to you via telegram?

**Comment by SoraKohaku** [comment]
sora88

**Comment by komporcoin** [comment]
@hsyaiban

Pada tanggal Sab, 30 Jun 2018 15.29 Founder Nur1Labs <
notifications@github.com menulis:

**Pull request closed without merging**
