### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by cleancoindev**

### CODE REVIEW

**Comment by ByoundG** [comment]
Dear cleancoindev,

would you tell me about the last update you have done on CryptonoteConfig.h

Obligingly,
Mr Qiu

**Comment by cleancoindev** [comment]
It was accidentally the pull requests were made.

However, I am having the hardest time getting Cryptonote to Build in debian
9.  I keep running into errors due to the new GCC etc.  This time I am
stuck on the error involving noexcept due to bad throws.

**Comment by cleancoindev** [comment]
I have tried compiling it in 5 different versions of linux now.  It has
taken me nearly 50 hours of work into this so far and I can't get
cryptonote to build.

**Comment by QuinnMallorry** [comment]
Please list steps to reproduce, and I'll spin up a VM here and step through it with you.

**Comment by cleancoindev** [comment]
Thanks.  The issue I had at first was compiler related.  Keeps being unable
to find C++ compiler or C or gcc etc etc.

I have tried it on debian 9 I have tried it on several other builds, ubuntu
etc none did any better.  I am now trying again on Cinnamon Linux Mint 64
bit with the same issue.

I can give you a copy of my virtual drive file if you wanted to check it
out in your own copy of virtual box.  Would that help?  If so I can upload
it to 4shared so you can download it and open it within virtual box.  I can
also provide you the file name of the specific OS if you wanted to try to
build it yourself from the ground up.

Basically the main problem is Cannot Get Compiler To Work.  When Make
process is done, errors.

There's been a lot of errors but I was able to work through some.

When a specific thing was commented out the next error showed up:

heres the error : policy cmp0046 is not set error on non-existent
dependency in add_dependencies

Then after that was solved, now errors with boost finding its dependencies.

I guess I need a list of the specific versions of the various software that
are the known best of all the dependancies.

Thanks for your help!

Enoch

Brief description of steps as follows:

1 created virtual machine using Linux mint cinnomon 64 current version
2 install make cmake via instructions
3 install boost via instructions
4 downloaded cryptocoin fork CleanCoin
5 modified files according to the instructions
6 attempted to compile with make as instructed
7 getting "no_CXX_COmpiler_FOund error and other directory related errors
9 Reinstalled boost in new directory...
10 now getting this error:
Imported targets not available for boost version

**Comment by cleancoindev** [comment]
Hello, Did I write the correct email address back?

Enoch

**Pull request closed without merging**
